### ISSUE TITLE
Slash-command Framework

### ISSUE THREAD

**Issue by DoggySazHi** [classAndrew/cow#7]
Working on a command framework to automatically accept message and slash commands, but Serenity/Rust is making this so much harder than I thought it would.

UNObot (C# via Discord.NET) has a generic-based framework but involves a ton of reflection, which isn't viable in Rust. https://github.com/DoggySazHi/UNObot/blob/master/src/UNObot/Services/CommandHandlingService.cs

It might be easier to re-implement most of the `StandardFramework` but replace the dispatch function. But then we would need a unified way for the framework to emit messages (interaction response, channel message, or reply). I've tried making a mixin for the `Message` class, but I'm not proficient enough with dealing with async lifetime bounds for this. Todo...

<img width="925" alt="image" src="https://user-images.githubusercontent.com/42221528/188066852-3436f60e-0fe7-4ae8-a602-fea0b0b572cc.png">

**Comment by classAndrew** [comment]
I'll take a look on Friday.

**Comment by classAndrew** [comment]
Yeah... I'm having a hard time with this. Each command would need to know if it's a slash command, meaning either we add a field to the `Context` or `Message`, or we add an extra argument to the command's function.

As for unifying the command's responses, I was thinking on just using a ton of macros, given that we know if a command was invoked as a slash command.

How are you creating a mixin for Rust structs?

**Comment by DoggySazHi** [comment]
We can make it an attribute, annotating each function with a custom
`#[SlashCommand]` annotation. Then we can load functions that have such
attributes and create the commands in Discord.

For mix-ins, I just defined a trait (`AutoResponse`) and made Message
`impl` the trait. Basically a mix-in. But I guess a macro would work as
well. I just want to reuse the same implementation but add extra attributes
to make it a slash command, so it must be aware of the context (how it was
invoked).

**Comment by DoggySazHi** [comment]
Turns out there's a semi-official way to make slash commands (https://docs.rs/poise/latest/poise/) using Serenity, although it's still experimental. I've continued work on our own command handler, but it *may* be easier to use something else.

**Comment by DoggySazHi** [comment]
OK, so I've got Poise to work (see 1ff12acb) and I'm currently testing it out. Embeds aren't overwritten for some reason, so I'll have to debug it even further. Hopefully I'll merge it into main soon.
